# docker-compose.yml file
version: '3'

services:
  
  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./pages:/usr/share/nginx/html
    ports:
      - "8080:80"

